const db = require("../repositories/postgres.repository");
const ApiError = require("../utils/ApiError");
const logActivity = require("../utils/logActivity");
const notifyUser = require("../utils/notifyUser");
const { hasPermission, isAssignableTaskMember } = require("../config/permissions");
const canModifyTask = (membership, globalRole, task, userId) => hasPermission(membership,"task:edit_any",globalRole) || (hasPermission(membership,"task:edit_own",globalRole) && task.createdBy === userId);
const canRemoveTask = (membership, globalRole, task, userId) => hasPermission(membership,"task:delete_any",globalRole) || (hasPermission(membership,"task:delete_own",globalRole) && task.createdBy === userId);
const ensureAssigneeIsMember = async (projectId, assignedTo) => { if (!assignedTo) return; const r = await db.query("SELECT pm.role, u.role AS user_role FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.user_id=$1 AND pm.project_id=$2",[assignedTo,projectId]); if(!isAssignableTaskMember(r.rows[0] && {role:r.rows[0].role,user:{role:r.rows[0].user_role}})) throw new ApiError(400,"Assigned user must be an assignable project member"); };
const rawTask = async (id) => db.toTask((await db.query("SELECT * FROM tasks WHERE id=$1 AND is_deleted=false",[id])).rows[0]);
const createTask = async ({payload,userId,userRole}) => { const {title,description,projectId,assignedTo,status="todo",priority="medium",dueDate}=payload; const membership=await db.getMembership(userId,projectId); if(!hasPermission(membership,"task:create",userRole)) throw new ApiError(403,"You do not have permission to create tasks"); await ensureAssigneeIsMember(projectId,assignedTo); const row=(await db.query("INSERT INTO tasks (title,description,status,priority,due_date,project_id,assigned_to,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[title,description || null,status,priority,dueDate || null,projectId,assignedTo || null,userId])).rows[0]; const task=await db.taskWithRelations(row.id); await logActivity({project:projectId,task:row.id,user:userId,action:"TASK_CREATED",metadata:{taskId:row.id,title}}); if(assignedTo) { const assignee=await db.findUser(assignedTo); if(assignee) notifyUser({type:"TASK_ASSIGNED",user:assignee,task}); } return task; };
const getTasks = async ({projectId,status,search,priority,assignedTo,page=1,limit=20,sortBy="createdAt",order="desc",sortOrder,userId,userRole}) => { const where=["t.is_deleted=false"], values=[]; const add=(sql,value)=>{values.push(value);where.push(sql.replace("?",`$${values.length}`));}; if(projectId){if(userRole!=="admin" && !await db.isMember(userId,projectId)) throw new ApiError(403,"You are not a member of this project");add("t.project_id=?",projectId);} else if(userRole!=="admin"){values.push(userId);where.push(`EXISTS (SELECT 1 FROM project_members access_pm WHERE access_pm.project_id=t.project_id AND access_pm.user_id=$${values.length})`);} if(status)add("t.status=?",status);if(priority)add("t.priority=?",priority);if(assignedTo)add("t.assigned_to=?",assignedTo);if(search){ const term=`%${search}%`; values.push(term,term); where.push(`(t.title ILIKE $${values.length-1} OR COALESCE(t.description,'') ILIKE $${values.length})`); }
  const pageNumber=Math.max(1,Number(page)||1), limitNumber=Math.min(100,Math.max(1,Number(limit)||20)); const columns={createdAt:"t.created_at",updatedAt:"t.updated_at",title:"t.title",dueDate:"t.due_date",priority:"t.priority",status:"t.status"};const sort=columns[sortBy]||columns.createdAt; const direction=(sortOrder||order)==="asc"?"ASC":"DESC";const filter=where.join(" AND "); const total=Number((await db.query(`SELECT COUNT(*) AS count FROM tasks t WHERE ${filter}`,values)).rows[0].count); values.push(limitNumber,(pageNumber-1)*limitNumber); const rows=(await db.query(`SELECT t.id FROM tasks t WHERE ${filter} ORDER BY ${sort} ${direction}, t.id ASC LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows; return {tasks:await Promise.all(rows.map(r=>db.taskWithRelations(r.id))),totalTasks:total,currentPage:pageNumber,totalPages:Math.ceil(total/limitNumber)||1}; };
const updateTask = async ({task,payload,userId,userRole}) => {const membership=await db.getMembership(userId,task.project);if(!canModifyTask(membership,userRole,task,userId))throw new ApiError(403,"You do not have permission to update this task");if(Object.hasOwn(payload,"assignedTo"))await ensureAssigneeIsMember(task.project,payload.assignedTo);const fields={title:"title",description:"description",status:"status",priority:"priority",dueDate:"due_date",assignedTo:"assigned_to"};const sets=[],values=[];for(const [key,column] of Object.entries(fields))if(Object.hasOwn(payload,key)){values.push(payload[key] || null);sets.push(`${column}=$${values.length}`);}if(!sets.length)return db.taskWithRelations(task._id);values.push(task._id);const previousAssignee=task.assignedTo;await db.query(`UPDATE tasks SET ${sets.join(", ")},updated_at=CURRENT_TIMESTAMP WHERE id=$${values.length}` ,values);const updated=await db.taskWithRelations(task._id);await logActivity({project:task.project,task:task._id,user:userId,action:task.status!==updated.status?"TASK_STATUS_UPDATED":"TASK_UPDATED",metadata:{taskId:task._id,from:task.status,to:updated.status}});if(payload.assignedTo&&payload.assignedTo!==previousAssignee){const u=await db.findUser(payload.assignedTo);if(u)notifyUser({type:"TASK_ASSIGNED",user:u,task:updated});}return updated;};
const deleteTask=async({task,user})=>{const membership=await db.getMembership(user.userId,task.project);if(!canRemoveTask(membership,user.role,task,user.userId))throw new ApiError(403,"You are not allowed to delete this task");await db.query("UPDATE tasks SET is_deleted=true,deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[task._id]);await logActivity({project:task.project,task:task._id,user:user.userId,action:"TASK_DELETED",metadata:{taskId:task._id}});return task;};
const addComment=async({task,userId,text,userRole})=>{const membership=await db.getMembership(userId,task.project);if(!canModifyTask(membership,userRole,task,userId))throw new ApiError(403,"You do not have permission to comment on this task");await db.query("INSERT INTO comments (task_id,user_id,comment) VALUES ($1,$2,$3)",[task._id,userId,text]);await logActivity({project:task.project,task:task._id,user:userId,action:"COMMENT_ADDED",metadata:{taskId:task._id,taskTitle:task.title}});return db.taskWithRelations(task._id);};
module.exports={addComment,canModifyTask,canRemoveTask,createTask,deleteTask,getTasks,rawTask,updateTask};
